### PR TITLE
[Bugfix] Folder can't be expanded after being collapsed in focus mode.

### LINKED ISSUE #17: [Bug] Focusing and Unfocusing a Folder Breaks Collapse
# Expected Behavior
After focusing on a folder, when unfocusing the same folder and collapsing the folder by clicking on it in the folder tree, the folder should collapse without issue.

# Actual Behavior
After focusing on a folder, unfocusing on the same folder and collapsing it by clicking on the folder in the folder tree collapses the folder the first time, but uncollapsing and collapsing the folder again breaks it. The behavior persists until I focus and unfocus on another folder. 

The "Collapse All" functionality also does not collapse the previously focused folder.

Thank you for your time!

### PR DESCRIPTION
**Pull request by Developer-Mike**
Closes #17 

Changes were made to the "substituteSetterForElement" function.

### CODE REVIEW

**Review by Michael679089 — APPROVED** [review]
Can confirm it works!

https://github.com/grochowski/obsidian-folder-focus-mode/assets/90962435/100b7e62-b727-4589-96a6-5f8e3a805b12

**Comment by Michael679089** [comment]
@Developer-Mike Where's the release of your pull request? I can't find it anymore in your fork.

**Comment by Developer-Mike** [comment]
@Michael679089 There are no releases right now. But I can make one right now (give me 5 minutes 😄).

**Comment by Developer-Mike** [comment]
Just made the [release](https://github.com/Developer-Mike/obsidian-folder-focus-mode/releases/tag/1.0.0).

**Comment by Michael679089** [comment]
> Just made the [release](https://github.com/Developer-Mike/obsidian-folder-focus-mode/releases/tag/1.0.0).

Thank you. :)

**Pull request merged**
